---
- hosts: postgres_servers
  collections:
    - community.postgresql
    - community.general
    - jfrog.platform
  vars_files:
    - ./vars.yml
  roles:
    - role: postgres
      when: postgres_enabled | bool

- hosts: artifactory_servers
  collections:
    - community.general
    - jfrog.platform
  vars_files:
    - ./vars.yml
  serial:
    - 1
    - 100%
  roles:
    - role: artifactory
      when: artifactory_enabled | bool

- hosts: xray_servers
  collections:
    - community.general
    - jfrog.platform
  vars_files:
    - ./vars.yml
  roles:
    - role: xray
      when: xray_enabled | bool

- hosts: distribution_servers
  collections:
    - community.general
    - jfrog.platform
  vars_files:
    - ./vars.yml
  roles:
    - role: distribution
      when: distribution_enabled | bool

- hosts: insight_servers
  collections:
    - community.general
    - ansible.posix
    - jfrog.platform
  vars_files:
    - ./vars.yml
  roles:
    - role: insight
      when: insight_enabled | bool