all:
  hosts:
    artifactory-server: 
      ansible_host: 10.95.123.37
    postgres-server: 
      ansible_host: 10.95.123.37
    xray-server: 
      ansible_host: 10.95.123.37
    distribution-server: 
      ansible_host: 10.95.123.37
    insight-server: 
      ansible_host: 10.95.123.37
  children:
    postgres_servers:
      hosts:
        postgres-server:
    xray_servers:
      hosts:
        xray-server:
    distribution_servers:
      hosts:
       distribution-server:
    insight_servers:
      hosts:
        insight-server:
    artifactory_servers:
      hosts:
        artifactory-server:
  vars:
    ansible_connection: ssh
    ansible_python_interpreter: /usr/bin/python3



