
init:
	terragrunt init

plan:
	terragrunt run-all plan

apply:
	terragrunt apply -auto-approve

destroy:
	terragrunt destroy -auto-approve

fmt:
	terragrunt hclfmt

validate:
	terragrunt validate-inputs


