# init
init-all:
	terragrunt run-all --terragrunt-non-interactive init 

init-jenkins:
	terragrunt run-all --terragrunt-non-interactive init --terragrunt-include-dir jenkins

init-sonarqube:
	terragrunt run-all --terragrunt-non-interactive init --terragrunt-include-dir sonarqube

init-nexus-repo:
	terragrunt run-all --terragrunt-non-interactive init --terragrunt-include-dir nexus-repo

init-splunk:
	terragrunt run-all --terragrunt-non-interactive init --terragrunt-include-dir splunk

init-sensu:
	terragrunt run-all --terragrunt-non-interactive init --terragrunt-include-dir sensu

init-postgres:
	terragrunt run-all --terragrunt-non-interactive init --terragrunt-include-dir postgres



# plan
plan-all:
	terragrunt run-all --terragrunt-non-interactive plan 

plan-jenkins:
	terragrunt run-all --terragrunt-non-interactive plan --terragrunt-include-dir jenkins

plan-sonarqube:
	terragrunt run-all --terragrunt-non-interactive plan --terragrunt-include-dir sonarqube

plan-nexus-repo:
	terragrunt run-all --terragrunt-non-interactive plan --terragrunt-include-dir nexus-repo

plan-splunk:
	terragrunt run-all --terragrunt-non-interactive plan --terragrunt-include-dir splunk

plan-sensu:
	terragrunt run-all --terragrunt-non-interactive plan --terragrunt-include-dir sensu

plan-postgres:
	terragrunt run-all --terragrunt-non-interactive plan --terragrunt-include-dir postgres


# create
create-all:
	terragrunt run-all --terragrunt-non-interactive apply 

create-jenkins:
	terragrunt run-all --terragrunt-non-interactive apply --terragrunt-include-dir jenkins

create-sonarqube:
	terragrunt run-all --terragrunt-non-interactive apply --terragrunt-include-dir sonarqube

create-nexus-repo:
	terragrunt run-all --terragrunt-non-interactive apply --terragrunt-include-dir nexus-repo

create-splunk:
	terragrunt run-all --terragrunt-non-interactive apply --terragrunt-include-dir splunk

create-sensu:
	terragrunt run-all --terragrunt-non-interactive apply --terragrunt-include-dir sensu

create-postgres:
	terragrunt run-all --terragrunt-non-interactive apply --terragrunt-include-dir postgres


# delete
delete-jenkins:
	terragrunt run-all --terragrunt-non-interactive destroy --terragrunt-include-dir jenkins 

delete-sonarqube:
	terragrunt run-all --terragrunt-non-interactive destroy --terragrunt-include-dir sonarqube 

delete-nexus-repo:
	terragrunt run-all --terragrunt-non-interactive destroy --terragrunt-include-dir nexus-repo

delete-splunk:
	terragrunt run-all --terragrunt-non-interactive destroy --terragrunt-include-dir splunk

delete-sensu:
	terragrunt run-all --terragrunt-non-interactive destroy --terragrunt-include-dir sensu

delete-all:
	terragrunt run-all --terragrunt-non-interactive destroy --terragrunt-ignore-dependency-errors

delete-postgres:
	terragrunt run-all --terragrunt-non-interactive destroy --terragrunt-include-dir postgres


# format
format-all:
	terragrunt run-all --terragrunt-non-interactive fmt 

format-jenkins:
	terragrunt run-all --terragrunt-non-interactive fmt --terragrunt-include-dir jenkins

format-sonarqube:
	terragrunt run-all --terragrunt-non-interactive fmt --terragrunt-include-dir sonarqube

format-nexus-repo:
	terragrunt run-all --terragrunt-non-interactive fmt --terragrunt-include-dir nexus-repo

format-splunk:
	terragrunt run-all --terragrunt-non-interactive fmt --terragrunt-include-dir splunk

format-sensu:
	terragrunt run-all --terragrunt-non-interactive fmt --terragrunt-include-dir sensu

format-postgres:
	terragrunt run-all --terragrunt-non-interactive fmt --terragrunt-include-dir postgres




# validate
validate-all:
	terragrunt run-all --terragrunt-non-interactive validate 

validate-jenkins:
	terragrunt run-all --terragrunt-non-interactive validate --terragrunt-include-dir jenkins

validate-sonarqube:
	terragrunt run-all --terragrunt-non-interactive validate --terragrunt-include-dir sonarqube

validate-nexus-repo:
	terragrunt run-all --terragrunt-non-interactive validate --terragrunt-include-dir nexus-repo

validate-splunk:
	terragrunt run-all --terragrunt-non-interactive validate --terragrunt-include-dir splunk

validate-sensu:
	terragrunt run-all --terragrunt-non-interactive validate --terragrunt-include-dir sensu

validate-postgres:
	terragrunt run-all --terragrunt-non-interactive validate --terragrunt-include-dir postgres



