postgresql_restarted_state: "restarted"
postgresql_python_library: python-psycopg2
postgresql_user: postgres
postgresql_group: postgres

postgresql_auth_method: "{{ ansible_fips  | ternary('scram-sha-256', 'md5') }}"

postgresql_unix_socket_directories:
  - /var/run/postgresql

postgresql_service_state: started
postgresql_service_enabled: true

postgresql_global_config_options:
  - option: unix_socket_directories
    value: '{{ postgresql_unix_socket_directories | join(",") }}'
  - option: log_directory
    value: 'log'

postgresql_hba_entries:
  - {type: local, database: all, user: postgres, auth_method: peer}
  - {type: local, database: all, user: all, auth_method: peer}
  - {type: host, database: all, user: all, address: '0.0.0.0/0', auth_method: "{{ postgresql_auth_method }}"}

postgresql_locales:
  - 'en_US.UTF-8'

postgresql_databases:
- name: sonar 
  lc_collate: 'en_US.UTF-8'
  lc_ctype: 'en_US.UTF-8'
  encoding: 'UTF-8'
  template: 'template0'
  login_host: 'localhost'
  login_password: 
  login_user: '{{ postgresql_user }}'
  login_unix_socket:
  port: 
  owner: postgresql_user
  state: 'present'

postgresql_users:
- name: jdoe
  password: 
  encrypted: 
  priv: 
  role_attr_flags: 
  db: 
  login_host: 'localhost'
  login_password: 
  login_user: '{{ postgresql_user }}'
  login_unix_socket: 
  port: 
  state: 'present'

postgres_users_no_log: true
